### PR TITLE
feat(maps-service): expose a GoogleMapsAPI service

### PR DESCRIPTION
**Pull request by tomtomau**
Now exporting a GoogleMapsAPI service.

This allows the consumer to create a service which depends on this service.

We currently use this for Geocoding addresses etc.

Also addresses issue in #61

### CODE REVIEW

**Comment by tomtomau** [comment]
OK had another issue as I'd brought my oldish fork up to date:

[Patched here](https://github.com/Vheissu/aurelia-google-maps/pull/64/commits/c64a00b81342423f53cd9214e61f45453ac1b7e6)

Do not like this one bit but because Typescript 1.6 only allows user defined type guards and not actual interface/implementation checking, this is the best we could come up with.

This became an issue for us as we are binding a complex ish data model for markers to the component which has it's own `address` property. As we additionally provide lat, lng we don't actually want it to be geocoded. Ultimately, I think we need a better way to handle this, but not sure whether we be so strict of forcing the consumer to pass us an array of [AddressMarker|LatLongMarker]

**Comment by Vheissu** [comment]
That's awesome @tomtomau if we can sort out those merge conflicts, I'll get this released in a new version ASAP.

**Comment by tomtomau** [comment]
Updated @Vheissu!

**Comment by Vheissu** [comment]
Beautiful. Love your work. Merging this in. Will release today

**Pull request merged**
