### PR TITLE
sendBoundsEvent() on setCenter()

### PR DESCRIPTION
**Pull request by Tseberechts**
I needed this, could be useful for y'all.

### CODE REVIEW

**Comment by Tseberechts** [comment]
on the last commit, the only thing I really did was sending an event when the api is loaded to make sure it's only included once.

**Comment by Vheissu** [comment]
@Tseberechts There are some merge conflicts, would you mind sorting these out and I'll merge? Thanks mate.

**Comment by Tseberechts** [comment]
@Vheissu There you go!

**Comment by Vheissu** [comment]
Thanks for that @Tseberechts all merged.

**Pull request merged**
