### PR TITLE
Update EventListener handlers

### PR DESCRIPTION
**Pull request by pgaultier**
Small fix to let ÈventListener` use data defined in `CustomEvent` 

```javascript
this.element.addEventListener(Events.START_MARKER_HIGHLIGHT, (data: any) => {
                let marker: any = self._renderedMarkers[data.index];
                // data.index should be replaced with data.detail.index 
                // .....
        });
```

### CODE REVIEW

**Comment by tomtomau** [comment]
Good catch! It looks like you might have had different line endings though? It's marked the entire file as changed

**Comment by pgaultier** [comment]
I’ll check it ASAP and push a better merge request ;-)

**Comment by pgaultier** [comment]
Sory for this mistake, I repushed everything with correct LF endings

**Comment by pgaultier** [comment]
Will you add it in aurelia-google-maps ?

**Comment by pgaultier** [comment]
Added ability to use `client` instead of `apiKey`

**Comment by Vheissu** [comment]
This is beautiful thank you @pgaultier

**Pull request merged**
