### PR TITLE
updated ignored files, corrected clearing of marker clusters, removed…

### PR DESCRIPTION
**Pull request by airboss001**
… repeated calls to renderCluster when each marker added to when collection fill is completed

### CODE REVIEW

**Comment by airboss001** [comment]
First time doing this, if I messed something up let me know.

**Comment by VMBindraban** [comment]
For starters, can you remove the `dist` directory from the PR?
This minimizes the code to review.

**Comment by airboss001** [comment]
Ok, trying to figure out how to backout the noise now.


________________________________

**Comment by airboss001** [comment]
closed this and added a pr for the specific files.

**Pull request closed without merging**
